### ISSUE TITLE
Fix transmeridian pass

### ISSUE THREAD

**Issue by zisi** [satnogs/satnogs-rotator-controller#12]

**Comment by cshields** [comment]
I would suggest allowing for a 45 degree overlap here..  (just from my experience of watching many passes having to move at crossing 0)

Maybe make this a configurable overlap? With my setup there is just one cable coming up (power) so the only risk is in twisting that too much, I could go around once or twice before even worrying about that. Other people might have more of a concern with lesser overlap.

**Comment by zisi** [comment]
Open this issue in new [repo](https://github.com/satnogs/satnogs-rotator-firmware).
