### ISSUE TITLE
Design case for rotator board

### ISSUE THREAD

**Issue by zisi** [satnogs/satnogs-rotator-controller#17]

**Comment by alexschultze** [comment]
I would recommend to change instead the size of the PCB to a common size (EURO, 160x100) and then you can buy COTS full metall boxes which gives you shielding.

**Comment by zisi** [comment]
The PCB is EURO size 100x80 mm and [metal box is 120x100x35 mm](http://grobotronics.com/project-box-120x100x35mm-aluminium.html).

New PCB is [here](https://github.com/zisi/satnogs-rotator-controller/tree/rotator-controller/PCB/satnogs_controller) and is under development.

**Comment by zisi** [comment]
PCB mounts and full metal box are [here](https://github.com/zisi/satnogs-rotator/commit/c98b194b95d9791257c96e89b16edfaa0ec56eef).
