### ISSUE TITLE
Place Arduino Code in "SatNOGS" subdirectory

### ISSUE THREAD

**Issue by alexschultze** [satnogs/satnogs-rotator-controller#4]
The Arduino IDE 1.6.2 complains that the sketch should be in a subdirectory named SatNOGS and suggests creating it.

**Comment by alexschultze** [comment]
![image](https://cloud.githubusercontent.com/assets/4873079/7618104/1e19a290-f9b0-11e4-9b16-dddf4e9b2a58.png)

**Comment by zisi** [comment]
Thank you @alexschultze. 
:beers: :rocket:
