### ISSUE TITLE
Include AccelStepper in the Git Repo

### ISSUE THREAD

**Issue by alexschultze** [satnogs/satnogs-rotator-controller#5]
AccelStepper is GPL license so we can just include the code within our git and be certain to have a specific version,

**Comment by alexschultze** [comment]
However does not seem to be supported by Arduino IDE ..

**Comment by zisi** [comment]
Hey, i can not understand your previous comment. I follow this "Install in the usual way: unzip the distribution zip file to the libraries sub-folder of your sketchbook." and it works.

**Comment by alexschultze** [comment]
I thought we could include the library files directly as part of the project, but I think that is not possible easily with the Arduino IDE now.
