### ISSUE TITLE
Firmware for 30 Stations milestone

### ISSUE THREAD

**Issue by zisi** [satnogs/satnogs-rotator-controller#8]
I2C/Wire library block main program, https://github.com/arduino/Arduino/issues/1476 , when we disconnect I2C cables. 
Use WDT with optiboot - bootloader.
Test homing function.
Use int instead of float or double.
Merge stepper with DC motor firmware.
Investigate to use timer for PID controller.
Test RS-485.

**Comment by jdvdperez** [comment]
Hey guys, there is not much activity here. Are we looking to implement all the features/changes included in the original post on Aug 17, 2015?

**Comment by zisi** [comment]
Hey! We are going to implement the above comment in new [PCB](https://github.com/satnogs/satnogs-rotator-controller/pull/27). We must open a discussion here or in IRC or in [satnogs community](https://community.satnogs.org/) about new architecture of rotator controller firmware.

**Comment by jdvdperez** [comment]
Sure. What type architecture do you have in mind so far? Event driven, State Machine, command based...

I need to get up to speed.

**Comment by jdvdperez** [comment]
I just had a quick overview of the DC and stepper motor controller. Looks like fun! Not much done yet I'd say, right?

**Comment by jdvdperez** [comment]
Comments on initial engagement conversations attached...
[List_of_requirements.txt](https://github.com/satnogs/satnogs-rotator-controller/files/796381/List_of_requirements.txt)

**Comment by zisi** [comment]
Open this issue in new repo.
